language: swift
osx_image: xcode11.3
script:
  - xcodebuild -scheme route -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 11,OS=13.3' clean build test
after_success:
  - bash <(curl -s https://codecov.io/bash) -J route -v
